### ISSUE TITLE
Control / Shift

### ISSUE THREAD

**Issue by iandoug** [jmjoy/keyboard-layout#1]
Nice.

Just wondering about having control on the thumb rather than the pinky. Muscle memory and all that.

Have you considered putting shift on the thumbs instead?

I would also probably rotate the dash, backslash and backtick buttons so that dash ends up on home row.

Mmm I suppose you use Emacs hence the backtick positiion. I don't, dash is more necessary for me.
My mods, FWIW :-)

http://www.keyboard-layout-editor.com/#/gists/19d0a997f25a91a36a5d5d2346d4442d

Cheers, Ian

**Comment by jmjoy** [comment]
Thank you for your advice!

Because I use the outside of the pinky to press the keys, which effectively prevents the pinky from wearing, I think shift is very convenient in that position, and ctrl is also often used a lot.

For the position of dash, in fact, I haven't figured out how to put it. It should be a good idea to exchange it with backticks.
